// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBneIht3ABykHbBUci-tscUg2Lsq6IqxGA',
    appId: '1:244473661405:web:158bb708ebdad3145d5834',
    messagingSenderId: '244473661405',
    projectId: 'score-score-56',
    authDomain: 'score-score-56.firebaseapp.com',
    storageBucket: 'score-score-56.appspot.com',
    measurementId: 'G-5102RQSSRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9p_ZQaQf8MuKpd0aU9kA1Jzt_IjJ5imo',
    appId: '1:244473661405:android:ee8b4a62fe7b791a5d5834',
    messagingSenderId: '244473661405',
    projectId: 'score-score-56',
    storageBucket: 'score-score-56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkt_Yua3XQgy9WMTEyYvnfi_j8lnDRzSE',
    appId: '1:244473661405:ios:862f93b8540657825d5834',
    messagingSenderId: '244473661405',
    projectId: 'score-score-56',
    storageBucket: 'score-score-56.appspot.com',
    iosBundleId: 'com.example.sportsScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkt_Yua3XQgy9WMTEyYvnfi_j8lnDRzSE',
    appId: '1:244473661405:ios:6c04eed60eda73a35d5834',
    messagingSenderId: '244473661405',
    projectId: 'score-score-56',
    storageBucket: 'score-score-56.appspot.com',
    iosBundleId: 'com.example.sportsScore.RunnerTests',
  );
}
